#!/bin/sh

source $PWD/.env

docker-compose -f ipfs.yaml up --no-recreate -d

if [ -n $1 ] && [ $1 = "a" ]; then
	ENCLAVE_CID=6 \
		NITRO_PROXY_PORT=8001 \
		AWS_REGION=$AWS_REGION \
		NITRO_KEY_ID=$NITRO_KEY_ID \
	  NITRO_KEYS_PATH=.nitro/key	\
		GENESIS_CONFIG_PATH=genesis.json \
		LAYER1_WS_PROVIDER_URL=$LAYER1_WS_PROVIDER_URL \
		LAYER1_KEY_PATH=.layer1/key \
		INIT_LAYER1_KEY=${INIT_LAYER1_KEY}	\
		LASTEST_TOPUP_HEIGHT=18896355 \
		TEA_ID=$TEA_ID \
		MACHINE_OWNER=$MACHINE_OWNER \
		LIBP2P_NODE_KEY_PATH=.libp2p/key \
		LIBP2P_BOOTNODES=$LIBP2P_BOOTNODES \
		LIBP2P_ENABLE_RELAY_PEERS="true" \
		LIBP2P_SUPPORTED_PROTOCOLS=tea-0.15 \
		LIBP2P_AGENT_PROTOCOL=tea-0.15 \
		LIBP2P_VERSION=0.15 \
		STATE_MAGIC_NUMBER=200 \
		APPLY_VALIDATOR="true" \
		PERSIST_PATH=.tokenstate/persist \
    IPFS_URL_BASE=http://localhost:5001 \
		RUST_BACKTRACE=full \
		MALLOC_CONF="prof:true" \
		./client-runner
else
	ENCLAVE_CID=6 \
		NITRO_PROXY_PORT=8001 \
		AWS_REGION=$AWS_REGION \
		NITRO_KEY_ID=$NITRO_KEY_ID \
	  NITRO_KEYS_PATH=.nitro/key	\
		GENESIS_CONFIG_PATH=genesis.json \
		TEA_ID=$TEA_ID \
		MACHINE_OWNER=$MACHINE_OWNER \
		LIBP2P_NODE_KEY_PATH=.libp2p/key \
		LIBP2P_BOOTNODES=$LIBP2P_BOOTNODES \
		LIBP2P_SUPPORTED_PROTOCOLS=tea-0.15 \
		LIBP2P_AGENT_PROTOCOL=tea-0.15 \
		LIBP2P_VERSION=0.15 \
		STATE_MAGIC_NUMBER=200 \
		PERSIST_PATH=.tokenstate/persist \
    IPFS_URL_BASE=http://localhost:5001 \
		RUST_BACKTRACE=full \
		MALLOC_CONF="prof:true" \
		./client-runner
fi