version: "3.1"

services:
  ipfs:
    image: ipfs/go-ipfs:v0.22.0
    container_name: ipfs
    network_mode: host
    volumes:
      - .ipfs_data:/data/ipfs
      - .ipfs:/ipfs/config
    environment:
      IPFS_SWARM_KEY_FILE: /ipfs/config/swarm.key
    entrypoint: []
    command: sh -c "/ipfs/config/start_ipfs daemon --migrate --enable-pubsub-experiment"

  parent-instance-client:
    image: tearust/parent-instance-client:alpha-1.1
    container_name: client
    network_mode: host
    volumes:
      - .log:/log
      - .tokenstate:/tokenstate
      - .libp2p:/libp2p
      - .layer1:/layer1
      - ./genesis.json:/tearust/data/genesis.json
      - .nitro:/nitro
    environment:
      ENCLAVE_CID: 6
      NITRO_PROXY_PORT: 8001
      AWS_REGION: ${AWS_REGION}
      NITRO_KEY_ID: ${NITRO_KEY_ID}
      LOG_FILE: /log/output.log
      NITRO_KEYS_PATH: /nitro/key
      GENESIS_CONFIG_PATH: /tearust/data/genesis.json
      LAYER1_WS_PROVIDER_URL: ${LAYER1_WS_PROVIDER_URL}
      LAYER1_KEY_PATH: /layer1/key
      INIT_LAYER1_KEY: ${INIT_LAYER1_KEY}
      LASTEST_TOPUP_HEIGHT: 8313477
      TEA_ID: "${TEA_ID}"
      MACHINE_OWNER: "${MACHINE_OWNER}"
      LIBP2P_NODE_KEY_PATH: /libp2p/key
      LIBP2P_BOOTNODES: ${LIBP2P_BOOTNODES}
      LIBP2P_ENABLE_RELAY_PEERS: "true"
      LIBP2P_SUPPORTED_PROTOCOLS: tea-0.15
      LIBP2P_AGENT_PROTOCOL: tea-0.15
      LIBP2P_VERSION: 0.15
      STATE_MAGIC_NUMBER: 200
      APPLY_VALIDATOR: "true"
      PERSIST_PATH: /tokenstate/persist
      IPFS_URL_BASE: http://localhost:5001
      RUST_BACKTRACE: full
      MALLOC_CONF: prof:true

      WAIT_HOSTS: localhost:5001
      WAIT_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
