version: "3.1"

services:

  togar3:
    image: tearust/togar3:latest
    container_name: togar3
    network_mode: host
    restart: always
    #ports:
    #  - 4006:4006
    #  - 3000:3000
    volumes:
      - ./game_env:/usr/src/app/.env
      - ./game_data:/usr/src/app/.data
