#!/bin/sh
set -e
user=ipfs
repo="$IPFS_PATH"

ipfs version

if [ ! -f "$IPFS_PATH/config" ]; then
  echo "Run ipfs init..."
  ipfs init
fi

ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001
ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8080

  # Set up the swarm key, if provided
SWARM_KEY_FILE="$repo/swarm.key"
SWARM_KEY_PERM=0400

  # Create a swarm key from a given environment variable
if [ ! -z "$IPFS_SWARM_KEY" ] ; then
  echo "Copying swarm key from variable..."
  echo -e "$IPFS_SWARM_KEY" >"$SWARM_KEY_FILE" || exit 1
  chmod $SWARM_KEY_PERM "$SWARM_KEY_FILE"
fi

  # Unset the swarm key variable
unset IPFS_SWARM_KEY

  # Check during initialization if a swarm key was provided and
  # copy it to the ipfs directory with the right permissions
  # WARNING: This will replace the swarm key if it exists
if [ ! -z "$IPFS_SWARM_KEY_FILE" ] ; then
  echo "Copying swarm key from file..."
  install -m $SWARM_KEY_PERM "$IPFS_SWARM_KEY_FILE" "$SWARM_KEY_FILE" || exit 1
fi

  # Unset the swarm key file variable
unset IPFS_SWARM_KEY_FILE


# ******* add for teaproject by jacky start ********

ipfs config --json Experimental.Libp2pStreamMounting true
# ipfs config --json Swarm.EnableRelayHop true
ipfs config --json Routing.Type '"dht"'

# to boot
ipfs bootstrap add /ip4/64.227.49.206/tcp/4001/p2p/12D3KooWScg336x2Rzc97ZnHbYAEd592P3DqkYJFZRQneGopjsyT


exec ipfs "$@"